Add default movies from company in search page
WhiteRabbitTheWorldIsYours/dashboard pull request #156
Opened 2020-12-16 08:58 UTC by mwaa

Please remember the [Contributing Guidelines](https://WhiteRabbitTheWorldIsYours/dashboard/blob/master/CONTRIBUTION.md) :heart:

## What does this PR do?

Simplifies movie search

## Recommendations for testing

- Use Production company rightsholder account
- Click on add movies
- The Search page should list movies that belong to the rights holder company
- There should be a single search field on the top right of screen. You can use text or imdb id to search for movies
- Movies listed after a search

## Links to relevant issues or information

Closes #120

2020-12-16 12:08 UTC, troggy requested changes
tested the functionality: works great 👍

Left some comments on the style and efficiency of the code

2020-12-16 12:08 UTC, troggy commented on frontend/src/stores/API.ts
> +  if (query !== 'undefined' && query !== '') {
if `query` is empty we don't want to execute this function at all. I suggest to shortcut the function with `if (!query) return [];` guard at the beginning plus avoid calling it whatsoever for empty queries (see the other comment)

2020-12-16 12:08 UTC, troggy commented on frontend/src/containers/MovieSearch.tsx
> +        .then((tmdbMovies) => setDisplay(tmdbMovies.map((current: any) => ({
consider using the common [tmdbToMovie](https://github.com/WhiteRabbitTheWorldIsYours/dashboard/blob/master/common/src/models.ts#L165) helper here. [Example](https://github.com/WhiteRabbitTheWorldIsYours/dashboard/blob/master/frontend/src/containers/components/PendingUserScreen.tsx#L18)

2020-12-16 12:08 UTC, troggy commented on frontend/src/stores/API.ts
>      const { results } = await fetch(
this is being called for `tt...` queries as well, consder `return`ing value right away after the `getMovieDetails` call above

2020-12-18 14:59 UTC, mwaa commented on frontend/src/containers/MovieSearch.tsx
> +        .then((tmdbMovies) => setDisplay(tmdbMovies.map((current: any) => ({
Can't use this now made comment for standardize movie interfaces

2020-12-18 16:20 UTC, troggy approved these changes
👍

2020-12-18 16:21 UTC, merged